# Generated by Django 3.2.12 on 2022-04-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0005_auto_20220411_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('to_address', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('successful', models.BooleanField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
