# Generated by Django 3.2.12 on 2022-04-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='invoice_attachment',
            field=models.CharField(default='filename.pdf', max_length=100),
            preserve_default=False,
        ),
    ]
