# Generated by Django 3.2.12 on 2022-04-12 19:32

from django.db import migrations, models
import django.db.models.deletion
import pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0005_auto_20220411_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to=pdf.models.generate_filename)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
