# Generated by Django 3.2.12 on 2022-04-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfimage',
            options={'verbose_name_plural': 'PDF Images'},
        ),
    ]
