# Generated by Django 3.2.12 on 2022-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
