# Generated by Django 3.2.12 on 2022-04-12 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20220411_1416'),
        ('invoice_item', '0002_auto_20220411_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_invoicing_party', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField(null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'verbose_name_plural': 'InvoicingPartyItems',
            },
        ),
        migrations.RemoveField(
            model_name='invoicingpartyitem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoicingpartyitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='InvoicedPartyItem',
        ),
        migrations.DeleteModel(
            name='InvoicingPartyItem',
        ),
    ]
