# Generated by Django 3.2.12 on 2022-04-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_item', '0003_auto_20220411_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name_plural': 'InvoicePartyItems'},
        ),
    ]
