# Generated by Django 3.2.12 on 2022-04-13 14:24

from django.db import migrations, models
import django.db.models.deletion
import invoice_attachment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0005_auto_20220411_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to=invoice_attachment.models.generate_filename)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
