# Generated by Django 3.2.12 on 2022-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the customer's first name", max_length=64)),
                ('last_name', models.CharField(blank=True, help_text="Enter the customer's last name", max_length=64)),
                ('email', models.EmailField(blank=True, help_text='Enter the customer email address', max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Enter the customer telephone number', max_length=10)),
                ('street', models.CharField(blank=True, help_text='Enter the street address', max_length=128)),
                ('city', models.CharField(blank=True, help_text='Enter the city', max_length=50)),
                ('state', models.CharField(blank=True, help_text='Enter the 2 digit state abbreviation', max_length=2)),
                ('zip', models.CharField(blank=True, help_text='Enter the 5 digit zipcode', max_length=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
